In [5]:
import numpy as np

# 1
data1 = np.random.rand(10,5)
data1

array([[0.62271784, 0.70031817, 0.45875005, 0.4177575 , 0.95229466],
       [0.2676805 , 0.36302306, 0.51729538, 0.14335498, 0.70462223],
       [0.1801114 , 0.89754795, 0.86146697, 0.04028945, 0.08101379],
       [0.36467217, 0.46530265, 0.56605045, 0.78164413, 0.01579085],
       [0.4947334 , 0.41000204, 0.8789139 , 0.49651858, 0.63063771],
       [0.52335671, 0.07042025, 0.13136594, 0.96855943, 0.40902484],
       [0.48268806, 0.28262249, 0.78819625, 0.34432021, 0.27693179],
       [0.73911458, 0.80758859, 0.77924963, 0.09469247, 0.7185089 ],
       [0.03933825, 0.15072319, 0.00503866, 0.14700585, 0.95275085],
       [0.58669369, 0.59470899, 0.98179157, 0.48842577, 0.73804308]])

In [7]:
data2 = np.arange(0,1,0.01)
data2

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [8]:
np.random.randn(10,10)

array([[-0.74981276,  2.53002664, -0.21659778,  0.58916313, -0.27370801,
        -2.16117084, -2.69289268, -1.23097372, -0.76269252, -0.40230002],
       [-0.13462484,  0.60439695, -0.57017889,  2.54914256,  0.15576272,
        -1.20066202, -0.34748956,  0.3972986 , -1.2561358 , -0.37478527],
       [-2.21928469,  0.9411725 , -1.28244908,  1.18273286,  0.95615102,
         0.46778771, -2.11266284, -1.66345819, -1.46589124, -0.09208373],
       [ 0.29926858, -1.40344739, -2.34531001, -0.26063645, -1.3619006 ,
        -0.60043488,  0.76455116,  1.55715859, -0.41218697,  0.95251883],
       [-0.11980047, -1.6083522 , -0.27732047,  1.29048275,  0.42222748,
        -1.05528378,  0.12996606,  1.33783533,  1.01955138, -1.15856232],
       [-1.59095798,  0.70114092,  0.83769399,  0.13013501,  0.75953215,
         0.76369278,  0.55113177,  0.29385918, -0.61922444,  1.01877268],
       [ 0.82429949,  0.60801504, -0.17570765, -1.17296329, -0.91588919,
         0.91541707, -0.9711298 ,  0.04529056

In [11]:
np.linspace(0,1,101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [14]:
for i in range(-6,5):
    print(i)

-6
-5
-4
-3
-2
-1
0
1
2
3
4


In [16]:
fw = open('test.txt', 'w+')
fw.write('one two three\nhaha')
fw.seek(4,0)
print(fw.readlines())


['two three\n', 'haha']


In [19]:
a = {'a':10}
b = a.get('b',2)
b

2

In [23]:
import json
a = json.loads('''{"a":"0","b":"2"}''')
print(type(a))

<class 'dict'>
