In [1]:
# 2019-4-1 课堂练习
# 1. 
import numpy as np
array = np.ones((5,5))
array[1:4, 1:4] = 0
print(array)
array3 = np.zeros((5, 5))
array3[0:5, [0, 4]] = 1
array3[[0, 4], 0:5] = 1
print(array3)
print('='*40)
# 2.
array2 = np.random.randn(4, 5)
print(array2)
array2[range(4), range(4)]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.52752794 -0.41345575 -1.79432216  1.00205312  2.10649315]
 [-0.16739944  0.57918384  0.29259698  1.55991642 -2.20591369]
 [ 0.27048907  0.92423257  0.80092251  0.67967652 -0.48849491]
 [ 0.14251751  1.26493833 -0.50178317  1.82530828 -1.56868941]]


array([0.52752794, 0.57918384, 0.80092251, 1.82530828])

In [30]:
# 书上P50 练习
# 3.3
array1 = np.arange(5)
array2 = np.arange(6, 11)
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 % array2)
print(array1 ** array2)

[ 6  8 10 12 14]
[-6 -6 -6 -6 -6]
[ 0  7 16 27 40]
[0.         0.14285714 0.25       0.33333333 0.4       ]
[0 1 2 3 4]
[      0       1     256   19683 1048576]


In [2]:
# 2 国际象棋棋盘
checkerboard = np.zeros((8, 8))
checkerboard[0:8:2, 0:8:2] = 1
checkerboard[1:8:2, 1:8:2] = 1
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [46]:
# 操作题
a1 = np.random.randn(2, 2)
a2 = np.random.randn(2, 2)
print(a1)
print(a2)
print(a1 * a2)

[[0.58881767 2.12125974]
 [0.39700184 0.05563642]]
[[-0.22029165 -0.86960923]
 [ 0.03089457 -1.49606521]]
[[-0.12971162 -1.84466704]
 [ 0.0122652  -0.08323571]]


In [36]:
# 将棋盘划分为2x2
# 横向分割
h1 = [x for x in np.hsplit(checkerboard, 2)]
# 纵向分割
v = [np.vsplit(h, 2) for h in h1]
print(v)


[[array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]]), array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])], [array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]]), array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])]]


[]