In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [7]:
wine_DF = pd.read_csv("./winequality.csv", delimiter=";")

In [16]:
wine_data = wine_DF.values[:50, :]

In [17]:
# 方法一: 数学降维
# 1. 标准化
sc = StandardScaler()
wine_std = sc.fit_transform(wine_data)


In [28]:
# 2. 对标准化数据转置, 构建协方差矩阵
cov_mat = np.cov(wine_std.T)

# 3. 获取特征值和特征向量
eifen_values, eigen_vectors = np.linalg.eig(cov_mat)
print(eifen_values.shape)
print("xxx")
print(eigen_vectors.shape)

(12,)
xxx
(12, 12)


In [27]:
# 4. 特征值总和
total = sum(eifen_values)
# 特征值比例
ration = [i/total for i in eifen_values]
print(len(ration))

50


In [29]:
# 5. 降维  协方差矩阵 * 特征向量
print(wine_std.shape)
print(eigen_vectors.shape)
wine_std.dot(eigen_vectors[:, :5])


(50, 12)
(12, 12)


array([[ 1.36564764,  0.4720026 ,  1.11031457,  1.00504191,  0.15417471],
       [-0.05018749,  0.79750082,  1.95384943, -0.09032724, -0.05366988],
       [ 0.3535635 ,  0.24401092,  1.30234563,  0.22169751,  0.09752688],
       [-3.16418264, -0.97329081, -1.94979796,  1.81342354, -0.57818242],
       [ 1.36564764,  0.4720026 ,  1.11031457,  1.00504191,  0.15417471],
       [ 1.22267158,  0.54560843,  0.97070229,  0.95371402, -0.01696395],
       [ 0.64947792,  0.00972282,  0.65375281,  0.7407173 , -1.07737445],
       [ 2.01105668, -0.79434676, -0.56069188,  1.35718334,  0.32142611],
       [ 0.78477238, -0.77431235, -0.19024306,  2.22953694,  0.9573147 ],
       [-1.205167  ,  2.03026079, -1.08577236, -0.93325341,  0.69743525],
       [ 0.80955264, -0.21375519,  0.72273863, -0.04552891, -1.17587519],
       [-1.205167  ,  2.03026079, -1.08577236, -0.93325341,  0.69743525],
       [ 3.03646666,  0.37932868, -0.03296844, -1.0293463 , -0.85518884],
       [-1.441007  , -1.95763858,  1.1

In [40]:
# 方法二: PCA 降维
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

pca = PCA(n_components=5).fit(wine_std)
wine_pca_new = pca.transform(wine_std)
ratio_pca = pca.explained_variance_ratio_
print(wine_pca_new)
print("xxx")
print(ratio_pca)

[[ 1.36564764  0.4720026  -1.11031457 -1.00504191  0.15417471]
 [-0.05018749  0.79750082 -1.95384943  0.09032724 -0.05366988]
 [ 0.3535635   0.24401092 -1.30234563 -0.22169751  0.09752688]
 [-3.16418264 -0.97329081  1.94979796 -1.81342354 -0.57818242]
 [ 1.36564764  0.4720026  -1.11031457 -1.00504191  0.15417471]
 [ 1.22267158  0.54560843 -0.97070229 -0.95371402 -0.01696395]
 [ 0.64947792  0.00972282 -0.65375281 -0.7407173  -1.07737445]
 [ 2.01105668 -0.79434676  0.56069188 -1.35718334  0.32142611]
 [ 0.78477238 -0.77431235  0.19024306 -2.22953694  0.9573147 ]
 [-1.205167    2.03026079  1.08577236  0.93325341  0.69743525]
 [ 0.80955264 -0.21375519 -0.72273863  0.04552891 -1.17587519]
 [-1.205167    2.03026079  1.08577236  0.93325341  0.69743525]
 [ 3.03646666  0.37932868  0.03296844  1.0293463  -0.85518884]
 [-1.441007   -1.95763858 -1.14463912  1.06944519  1.27061425]
 [-4.05930022  2.15471115 -1.64611132  0.81860366 -0.96983209]
 [-4.1007975   2.17559175 -1.59842249  0.90799786 -0.89

In [41]:
help(pca)

Help on PCA in module sklearn.decomposition.pca object:

class PCA(sklearn.decomposition.base._BasePCA)
 |  PCA(n_components=None, copy=True, whiten=False, svd_solver='auto', tol=0.0, iterated_power='auto', random_state=None)
 |  
 |  Principal component analysis (PCA)
 |  
 |  Linear dimensionality reduction using Singular Value Decomposition of the
 |  data to project it to a lower dimensional space.
 |  
 |  It uses the LAPACK implementation of the full SVD or a randomized truncated
 |  SVD by the method of Halko et al. 2009, depending on the shape of the input
 |  data and the number of components to extract.
 |  
 |  It can also use the scipy.sparse.linalg ARPACK implementation of the
 |  truncated SVD.
 |  
 |  Notice that this class does not support sparse input. See
 |  :class:`TruncatedSVD` for an alternative with sparse data.
 |  
 |  Read more in the :ref:`User Guide <PCA>`.
 |  
 |  Parameters
 |  ----------
 |  n_components : int, float, None or string
 |      Number of co